notifications:
  email:
    on_success: never
    on_failure: change

language: node_js

script:
  - script/travis-ci-build.sh

git:
  depth: 10

sudo: false

os:
  - linux
  - osx

env:
  global:
    - APM_TEST_PACKAGES="intentions language-tex"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

before_install:
  - script/travis-ci-before-install.sh

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - texlive
    - texlive-doc-en
    - texlive-latex-base-doc

;branches:
  only:
    - master
