notifications:
  email:
    on_success: never
    on_failure: change

script:
  - script/travis-ci-build.sh

git:
  depth: 10

sudo: false

os:
  - linux
  - osx

env:
  global:
    - APM_TEST_PACKAGES="intentions language-tex"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

before_install:
  -  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://mirror.ctan.org/systems/mac/mactex/BasicTeX.pkg -O "/tmp/BasicTeX.pkg"; sudo installer -pkg "/tmp/BasicTeX.pkg" -target /; rm /tmp/BasicTeX.pkg; export PATH=/usr/texbin:$PATH; fi

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - texlive-full

;branches:
  only:
    - master
